SPECTRA = \
{u'CANCO': {u'Labels': [u'CA', u'N', u'CO-1'],
            u'MinNumberPeaksPerSpinSystem': 1,
            u'PeakDescriptions': [{u'dimensions': [u'CA', u'N', u'CO-1'], u'fraction': 1}]},
 u'CANCOCX': {u'Labels': [u'CA', u'N', u'CO-1', u'CX-1'],
              u'MinNumberPeaksPerSpinSystem': 2,
              u'PeakDescriptions': [{u'dimensions': [u'CA', u'N', u'CO-1', u'CO-1'], u'fraction': 1},
                                    {u'dimensions': [u'CA', u'N', u'CO-1', u'CA-1'], u'fraction': 1},
                                    {u'dimensions': [u'CA', u'N', u'CO-1', u'CB-1'], u'fraction': 1},
                                    {u'dimensions': [u'CA', u'N', u'CO-1', u'CG-1'], u'fraction': 1},
                                    {u'dimensions': [u'CA', u'N', u'CO-1', u'CD-1'], u'fraction': 1},
                                    {u'dimensions': [u'CA', u'N', u'CO-1', u'CE-1'], u'fraction': 1},
                                    {u'dimensions': [u'CA', u'N', u'CO-1', u'CZ-1'], u'fraction': 1}]},
 u'CBCANH': {u'Labels': [u'CA/CB', u'H', u'N'],
             u'MinNumberPeaksPerSpinSystem': 2,
             u'PeakDescriptions': [{u'dimensions': [u'CA', u'H', u'N'], u'fraction': 1},
                                   {u'dimensions': [u'CB', u'H', u'N'], u'fraction': 0.95},
                                   {u'dimensions': [u'CA', u'H+1', u'N+1'], u'fraction': 1},
                                   {u'dimensions': [u'CB', u'H+1', u'N+1'], u'fraction': 0.95}]},
 u'CBCAcoNH': {u'Labels': [u'CA/CB', u'H+1', u'N+1'],
               u'MinNumberPeaksPerSpinSystem': 2,
               u'PeakDescriptions': [{u'dimensions': [u'CA', u'H+1', u'N+1'], u'fraction': 1},
                                     {u'dimensions': [u'CB', u'H+1', u'N+1'], u'fraction': 0.95}]},
 u'CCcoNH': {u'Labels': [u'CX-1', u'N', u'H'],
             u'MinNumberPeaksPerSpinSystem': 2,
             u'PeakDescriptions': [{u'dimensions': [u'CA-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'CB-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'CG-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'CD-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'CE-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'CZ-1', u'N', u'H'], u'fraction': 1}],
             u'ResonanceLimit': {u'ALA': [u'H', u'N', u'CA', u'CB'],
                                 u'ARG': [u'H', u'N', u'CA', u'CB', u'CG', u'CD', u'CZ'],
                                 u'ASN': [u'H', u'N', u'CA', u'CB', u'CG'],
                                 u'ASP': [u'H', u'N', u'CA', u'CB', u'CG'],
                                 u'CYS': [u'H', u'N', u'CA', u'CB'],
                                 u'GLN': [u'H', u'N', u'CA', u'CB', u'CG', u'CD'],
                                 u'GLU': [u'H', u'N', u'CA', u'CB', u'CG', u'CD'],
                                 u'GLY': [u'H', u'N', u'CA'],
                                 u'HIS': [u'H', u'N', u'CA', u'CB'],
                                 u'ILE': [u'H', u'N', u'CA', u'CB', u'CG1', u'CG2', u'CD1'],
                                 u'LEU': [u'H', u'N', u'CA', u'CB', u'CG', u'CD1', u'CD2'],
                                 u'LYS': [u'H', u'N', u'CA', u'CB', u'CG', u'CD', u'CE'],
                                 u'MET': [u'H', u'N', u'CA', u'CB', u'CG', u'CE'],
                                 u'PHE': [u'H', u'N', u'CA', u'CB'],
                                 u'SER': [u'H', u'N', u'CA', u'CB'],
                                 u'THR': [u'H', u'N', u'CA', u'CB', u'CG2'],
                                 u'TRP': [u'H', u'N', u'CA', u'CB'],
                                 u'TYR': [u'H', u'N', u'CA', u'CB'],
                                 u'VAL': [u'H', u'N', u'CA', u'CB', u'CG1', u'CG2']}},
 u'HBHAcoNH': {u'Labels': [u'HA/HB-1', u'N', u'H'],
               u'MinNumberPeaksPerSpinSystem': 2,
               u'PeakDescriptions': [{u'dimensions': [u'HA-1', u'N', u'H'], u'fraction': 1},
                                     {u'dimensions': [u'HB-1', u'N', u'H'], u'fraction': 1}]},
 u'HNCA': {u'Labels': [u'H', u'N', u'CA'],
           u'MinNumberPeaksPerSpinSystem': 1,
           u'PeakDescriptions': [{u'dimensions': [u'H', u'N', u'CA'], u'fraction': 1},
                                 {u'dimensions': [u'H', u'N', u'CA-1'], u'fraction': 1}]},
 u'HNCACB': {u'Labels': [u'H', u'N', u'CA/CB'],
             u'MinNumberPeaksPerSpinSystem': 2,
             u'PeakDescriptions': [{u'dimensions': [u'H', u'N', u'CA'], u'fraction': 1},
                                   {u'dimensions': [u'H', u'N', u'CB'], u'fraction': 0.95},
                                   {u'dimensions': [u'H', u'N', u'CA-1'], u'fraction': 1},
                                   {u'dimensions': [u'H', u'N', u'CB-1'], u'fraction': 0.95}]},
 u'HNCO': {u'Labels': [u'H', u'N', u'CO-1'],
           u'MinNumberPeaksPerSpinSystem': 1,
           u'PeakDescriptions': [{u'dimensions': [u'H', u'N', u'CO-1'], u'fraction': 1}]},
 u'HNcaCO': {u'Labels': [u'H', u'N', u'CO'],
             u'MinNumberPeaksPerSpinSystem': 1,
             u'PeakDescriptions': [{u'dimensions': [u'H', u'N', u'CO'], u'fraction': 1},
                                   {u'dimensions': [u'H', u'N', u'CO-1'], u'fraction': 1}]},
 u'HNcoCA': {u'Labels': [u'H', u'N', u'CA'],
             u'MinNumberPeaksPerSpinSystem': 1,
             u'PeakDescriptions': [{u'dimensions': [u'H', u'N', u'CA-1'], u'fraction': 1}]},
 u'HNcoCACB': {u'Labels': [u'H', u'N', u'CA/CB-1'],
               u'MinNumberPeaksPerSpinSystem': 2,
               u'PeakDescriptions': [{u'dimensions': [u'H', u'N', u'CA-1'], u'fraction': 1},
                                     {u'dimensions': [u'H', u'N', u'CB-1'], u'fraction': 0.95}]},
 u'HSQC': {u'Labels': [u'H', u'N'],
           u'MinNumberPeaksPerSpinSystem': 1,
           u'PeakDescriptions': [{u'dimensions': [u'H', u'N'], u'fraction': 1}]},
 u'HccoNH': {u'Labels': [u'HX-1', u'N', u'H'],
             u'MinNumberPeaksPerSpinSystem': 2,
             u'PeakDescriptions': [{u'dimensions': [u'HA-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'HB-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'HG-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'HD-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'HE-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'HH-1', u'N', u'H'], u'fraction': 1},
                                   {u'dimensions': [u'HZ-1', u'N', u'H'], u'fraction': 1}],
             u'ResonanceLimit': {u'ALA': [u'H', u'N', u'HA', u'HB'],
                                 u'ARG': [u'H', u'N', u'HA', u'HB2', u'HB3', u'HG2', u'HG3', u'HD2', u'HD3'],
                                 u'ASN': [u'H', u'N', u'HA', u'HB2', u'HB3'],
                                 u'ASP': [u'H', u'N', u'HA', u'HB2', u'HB3'],
                                 u'CYS': [u'H', u'N', u'HA', u'HB2', u'HB3'],
                                 u'GLN': [u'H', u'N', u'HA', u'HB2', u'HB3', u'HG2', u'HG3'],
                                 u'GLU': [u'H', u'N', u'HA', u'HB2', u'HB3', u'HG2', u'HG3'],
                                 u'GLY': [u'H', u'N', u'HA2', u'HA3'],
                                 u'HIS': [u'H', u'N', u'HA', u'HB2', u'HB3'],
                                 u'ILE': [u'H', u'N', u'HA', u'HB', u'HG12', u'HG13', u'HG2', u'HD1'],
                                 u'LEU': [u'H', u'N', u'HA', u'HB2', u'HB3', u'HD1', u'HD2'],
                                 u'LYS': [u'H',
                                          u'N',
                                          u'HA',
                                          u'HB2',
                                          u'HB3',
                                          u'HG2',
                                          u'HG3',
                                          u'HD2',
                                          u'HD3',
                                          u'HE2',
                                          u'HE3'],
                                 u'MET': [u'H', u'N', u'HA', u'HB2', u'HB3', u'HG2', u'HG3', u'HE'],
                                 u'PHE': [u'H', u'N', u'HA', u'HB2', u'HB3'],
                                 u'SER': [u'H', u'N', u'HA', u'HB2', u'HB3'],
                                 u'THR': [u'H', u'N', u'HA', u'HB', u'HG2'],
                                 u'TRP': [u'H', u'N', u'HA', u'HB2', u'HB3'],
                                 u'TYR': [u'H', u'N', u'HA', u'HB2', u'HB3'],
                                 u'VAL': [u'H', u'N', u'HA', u'HB', u'HG1', u'HG2']}},
 u'NCA': {u'Labels': [u'N', u'CA'],
          u'MinNumberPeaksPerSpinSystem': 1,
          u'PeakDescriptions': [{u'dimensions': [u'N', u'CA'], u'fraction': 1}]},
 u'NCACX': {u'Labels': [u'N', u'CA', u'CX'],
            u'MinNumberPeaksPerSpinSystem': 2,
            u'PeakDescriptions': [{u'dimensions': [u'N', u'CA', u'CO'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CA', u'CA'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CA', u'CB'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CA', u'CG'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CA', u'CD'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CA', u'CE'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CA', u'CZ'], u'fraction': 1}]},
 u'NCO': {u'Labels': [u'N', u'CO-1'],
          u'MinNumberPeaksPerSpinSystem': 1,
          u'PeakDescriptions': [{u'dimensions': [u'N', u'CO-1'], u'fraction': 1}]},
 u'NCOCX': {u'Labels': [u'N', u'CO-1', u'CX-1'],
            u'MinNumberPeaksPerSpinSystem': 2,
            u'PeakDescriptions': [{u'dimensions': [u'N', u'CO-1', u'CA-1'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CO-1', u'CB-1'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CO-1', u'CG-1'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CO-1', u'CD-1'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CO-1', u'CE-1'], u'fraction': 1},
                                  {u'dimensions': [u'N', u'CO-1', u'CZ-1'], u'fraction': 1}]}}